theme: jekyll-theme-minimal
title: Jimena Guallar-Blasco
profile_picture: https://drive.google.com/file/d/1-VvcEmYNFjaHgbVdpenobUNNZaZEEVi6/view?usp=sharing 
description: Undergraduate student at the Johns Hopkins Whiting School of Engineering doing Natural Language Processing Research at the Center for Language and Speech Processing (advised by Benjamin Van Durme).


