url: "https://jguallar-blasco.github.io/jguallar-blasco"
theme: jekyll-theme-minimal
lang: "en"
author: "Jimena Guallar-Blasco"
title: "Jimena Guallar-Blasco"
description: Undergraduate student at the Johns Hopkins Whiting School of Engineering doing Natural Language Processing Research at the Center for Language and Speech Processing (advised by Benjamin Van Durme).
favicon: /assets/images/profile.png 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"
logo: "/assets/images/profile.png" # leave blank if you don't want a logo

background-img: "../img/intro-bg.jpg"

###########
# Contact #
###########

email: "jgualla1@jh.edu"

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'


