title: Jimena Guallar-Blasco
description: NLP @ Johns Hopkins University
logo: assets/headshot.jpg
url: "https://jguallar-blasco.github.io"

plugins:
  - jekyll-seo-tag

author: jguallar-blasco
social:
  name: Jimena Guallar-Blasco
  links:
    - https://github.com/jguallar-blasco
