theme: jekyll-theme-minimal
title: Jimena Guallar-Blasco
profile_picture: https://github.com/jguallar-blasco/jguallar-blasco.github.io/blob/main/image.png
description: Undergraduate student at the Johns Hopkins Whiting School of Engineering doing Natural Language Processing Research at the Center for Language and Speech Processing (advised by Benjamin Van Durme).
