url: "https://jguallar-blasco.github.io/jguallar-blasco"
theme: jekyll-theme-minimal
title: Jimena Guallar-Blasco
me-img: /assets/images/profile.png 
author_blurb: "hiii"
author_blurb_image: /assets/images/profile.png 
description: Undergraduate student at the Johns Hopkins Whiting School of Engineering doing Natural Language Processing Research at the Center for Language and Speech Processing (advised by Benjamin Van Durme).


